apiVersion: v1
kind: Service
metadata:
  name: web-devops
  labels:
    app: devops-app
spec:
  type: NodePort
  selector:
    app: devops-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
