---
- name: Create empty file and ACLs
  hosts: all
  become: yes

  vars:
    acl_data:
      stapp01:
        path: /opt/dba/blog.txt
        etype: group
        permissions: r
      stapp02:
        path: /opt/dba/story.txt
        etype: user
        permissions: rw
      stapp03:
        path: /opt/dba/media.txt
        etype: group
        permissions: rw

  tasks:
    - name: Create empty file
      file:
        path: "{{ acl_data[ansible_hostname].path }}"
        state: touch
      when: ansible_hostname in acl_data

    - name: Set ACLs on the file
      acl:
        path: "{{ acl_data[ansible_hostname].path }}"
        entity: "{{ ansible_user }}"
        etype: "{{ acl_data[ansible_hostname].etype }}"
        permissions: "{{ acl_data[ansible_hostname].permissions }}"
        state: present
      when: ansible_hostname in acl_data
